# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jonathan/Programming/Python/mist/gui/forms/mainwindow.ui'
#
# Created: Wed Nov 30 13:34:56 2011
#      by: pyside-uic @pyside_tools_VERSION@ running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(913, 661)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwindow.sizePolicy().hasHeightForWidth())
        mainwindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        mainwindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(mainwindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 913, 25))
        self.menuBar.setObjectName("menuBar")
        self.fileMenu = QtGui.QMenu(self.menuBar)
        self.fileMenu.setObjectName("fileMenu")
        self.editMenu = QtGui.QMenu(self.menuBar)
        self.editMenu.setObjectName("editMenu")
        self.addToPlaylistMenu = QtGui.QMenu(self.editMenu)
        self.addToPlaylistMenu.setObjectName("addToPlaylistMenu")
        self.addToRepositoryMenu = QtGui.QMenu(self.editMenu)
        self.addToRepositoryMenu.setObjectName("addToRepositoryMenu")
        self.viewMenu = QtGui.QMenu(self.menuBar)
        self.viewMenu.setObjectName("viewMenu")
        self.helpMenu = QtGui.QMenu(self.menuBar)
        self.helpMenu.setObjectName("helpMenu")
        self.playbackMenu = QtGui.QMenu(self.menuBar)
        self.playbackMenu.setObjectName("playbackMenu")
        mainwindow.setMenuBar(self.menuBar)
        self.playbackControlsBar = QtGui.QToolBar(mainwindow)
        self.playbackControlsBar.setMovable(False)
        self.playbackControlsBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea)
        self.playbackControlsBar.setFloatable(False)
        self.playbackControlsBar.setObjectName("playbackControlsBar")
        mainwindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.playbackControlsBar)
        self.leftDock_2 = QtGui.QDockWidget(mainwindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftDock_2.sizePolicy().hasHeightForWidth())
        self.leftDock_2.setSizePolicy(sizePolicy)
        self.leftDock_2.setMinimumSize(QtCore.QSize(250, 582))
        self.leftDock_2.setMaximumSize(QtCore.QSize(250, 524287))
        self.leftDock_2.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.leftDock_2.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.leftDock_2.setObjectName("leftDock_2")
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.songCountLabel = QtGui.QLabel(self.dockWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Pro")
        font.setPointSize(11)
        self.songCountLabel.setFont(font)
        self.songCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songCountLabel.setObjectName("songCountLabel")
        self.verticalLayout.addWidget(self.songCountLabel)
        self.collectionsListFrame = QtGui.QFrame(self.dockWidgetContents_4)
        self.collectionsListFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.collectionsListFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.collectionsListFrame.setObjectName("collectionsListFrame")
        self.gridLayout = QtGui.QGridLayout(self.collectionsListFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.collectionsList = QtGui.QTreeWidget(self.collectionsListFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectionsList.sizePolicy().hasHeightForWidth())
        self.collectionsList.setSizePolicy(sizePolicy)
        self.collectionsList.setAutoFillBackground(False)
        self.collectionsList.setFrameShape(QtGui.QFrame.StyledPanel)
        self.collectionsList.setFrameShadow(QtGui.QFrame.Plain)
        self.collectionsList.setLineWidth(1)
        self.collectionsList.setMidLineWidth(1)
        self.collectionsList.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.collectionsList.setHeaderHidden(False)
        self.collectionsList.setObjectName("collectionsList")
        self.gridLayout.addWidget(self.collectionsList, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.collectionsListFrame)
        self.searchInput = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.searchInput.setObjectName("searchInput")
        self.verticalLayout.addWidget(self.searchInput)
        self.tagNameFilter1 = QtGui.QComboBox(self.dockWidgetContents_4)
        self.tagNameFilter1.setObjectName("tagNameFilter1")
        self.verticalLayout.addWidget(self.tagNameFilter1)
        self.tagNameFilter2 = QtGui.QComboBox(self.dockWidgetContents_4)
        self.tagNameFilter2.setObjectName("tagNameFilter2")
        self.verticalLayout.addWidget(self.tagNameFilter2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.songInfo = QtGui.QGroupBox(self.dockWidgetContents_4)
        self.songInfo.setObjectName("songInfo")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.songInfo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.songTitleLabel = QtGui.QLabel(self.songInfo)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Pro")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.songTitleLabel.setFont(font)
        self.songTitleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songTitleLabel.setObjectName("songTitleLabel")
        self.verticalLayout_3.addWidget(self.songTitleLabel)
        self.songArtistLabel = QtGui.QLabel(self.songInfo)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Pro")
        font.setPointSize(11)
        self.songArtistLabel.setFont(font)
        self.songArtistLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songArtistLabel.setObjectName("songArtistLabel")
        self.verticalLayout_3.addWidget(self.songArtistLabel)
        self.songAlbumLabel = QtGui.QLabel(self.songInfo)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Pro")
        font.setPointSize(11)
        self.songAlbumLabel.setFont(font)
        self.songAlbumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songAlbumLabel.setObjectName("songAlbumLabel")
        self.verticalLayout_3.addWidget(self.songAlbumLabel)
        self.verticalLayout.addWidget(self.songInfo)
        self.taskLabel = QtGui.QLabel(self.dockWidgetContents_4)
        self.taskLabel.setObjectName("taskLabel")
        self.verticalLayout.addWidget(self.taskLabel)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents_4)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.leftDock_2.setWidget(self.dockWidgetContents_4)
        mainwindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.leftDock_2)
        self.importSongAction = QtGui.QAction(mainwindow)
        self.importSongAction.setObjectName("importSongAction")
        self.deleteSongAction = QtGui.QAction(mainwindow)
        self.deleteSongAction.setObjectName("deleteSongAction")
        self.playPauseAction = QtGui.QAction(mainwindow)
        self.playPauseAction.setObjectName("playPauseAction")
        self.previousAction = QtGui.QAction(mainwindow)
        self.previousAction.setObjectName("previousAction")
        self.nextAction = QtGui.QAction(mainwindow)
        self.nextAction.setObjectName("nextAction")
        self.quitAction = QtGui.QAction(mainwindow)
        self.quitAction.setObjectName("quitAction")
        self.importDirectoryAction = QtGui.QAction(mainwindow)
        self.importDirectoryAction.setObjectName("importDirectoryAction")
        self.newPlaylistAction = QtGui.QAction(mainwindow)
        self.newPlaylistAction.setObjectName("newPlaylistAction")
        self.newRepositoryAction = QtGui.QAction(mainwindow)
        self.newRepositoryAction.setObjectName("newRepositoryAction")
        self.deleteCollectionAction = QtGui.QAction(mainwindow)
        self.deleteCollectionAction.setObjectName("deleteCollectionAction")
        self.modifyCollectionAction = QtGui.QAction(mainwindow)
        self.modifyCollectionAction.setObjectName("modifyCollectionAction")
        self.enqueueSongsAction = QtGui.QAction(mainwindow)
        self.enqueueSongsAction.setObjectName("enqueueSongsAction")
        self.clearSongQueueAction = QtGui.QAction(mainwindow)
        self.clearSongQueueAction.setObjectName("clearSongQueueAction")
        self.deleteTagsAction = QtGui.QAction(mainwindow)
        self.deleteTagsAction.setObjectName("deleteTagsAction")
        self.renameTagsAction = QtGui.QAction(mainwindow)
        self.renameTagsAction.setObjectName("renameTagsAction")
        self.fileMenu.addAction(self.importSongAction)
        self.fileMenu.addAction(self.importDirectoryAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.newPlaylistAction)
        self.fileMenu.addAction(self.newRepositoryAction)
        self.fileMenu.addAction(self.modifyCollectionAction)
        self.fileMenu.addAction(self.deleteCollectionAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.quitAction)
        self.editMenu.addAction(self.addToPlaylistMenu.menuAction())
        self.editMenu.addAction(self.addToRepositoryMenu.menuAction())
        self.editMenu.addAction(self.enqueueSongsAction)
        self.editMenu.addAction(self.clearSongQueueAction)
        self.editMenu.addAction(self.deleteSongAction)
        self.playbackMenu.addAction(self.playPauseAction)
        self.playbackMenu.addSeparator()
        self.playbackMenu.addAction(self.previousAction)
        self.playbackMenu.addAction(self.nextAction)
        self.playbackMenu.addSeparator()
        self.menuBar.addAction(self.fileMenu.menuAction())
        self.menuBar.addAction(self.editMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.playbackMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())
        self.playbackControlsBar.addAction(self.previousAction)
        self.playbackControlsBar.addAction(self.playPauseAction)
        self.playbackControlsBar.addAction(self.nextAction)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        mainwindow.setWindowTitle(QtGui.QApplication.translate("mainwindow", "Mist", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("mainwindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("mainwindow", "Song", None, QtGui.QApplication.UnicodeUTF8))
        self.addToPlaylistMenu.setTitle(QtGui.QApplication.translate("mainwindow", "Add to Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.addToRepositoryMenu.setTitle(QtGui.QApplication.translate("mainwindow", "Add to Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.viewMenu.setTitle(QtGui.QApplication.translate("mainwindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("mainwindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackMenu.setTitle(QtGui.QApplication.translate("mainwindow", "&Playback", None, QtGui.QApplication.UnicodeUTF8))
        self.playbackControlsBar.setWindowTitle(QtGui.QApplication.translate("mainwindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.songCountLabel.setText(QtGui.QApplication.translate("mainwindow", "Song Count", None, QtGui.QApplication.UnicodeUTF8))
        self.collectionsList.headerItem().setText(0, QtGui.QApplication.translate("mainwindow", "Collections", None, QtGui.QApplication.UnicodeUTF8))
        self.searchInput.setPlaceholderText(QtGui.QApplication.translate("mainwindow", "      Search", None, QtGui.QApplication.UnicodeUTF8))
        self.songInfo.setTitle(QtGui.QApplication.translate("mainwindow", "Playing:", None, QtGui.QApplication.UnicodeUTF8))
        self.songTitleLabel.setText(QtGui.QApplication.translate("mainwindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.songArtistLabel.setText(QtGui.QApplication.translate("mainwindow", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.songAlbumLabel.setText(QtGui.QApplication.translate("mainwindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.taskLabel.setText(QtGui.QApplication.translate("mainwindow", "Task Label", None, QtGui.QApplication.UnicodeUTF8))
        self.importSongAction.setText(QtGui.QApplication.translate("mainwindow", "Import Song", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSongAction.setText(QtGui.QApplication.translate("mainwindow", "Delete Song", None, QtGui.QApplication.UnicodeUTF8))
        self.playPauseAction.setText(QtGui.QApplication.translate("mainwindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.playPauseAction.setToolTip(QtGui.QApplication.translate("mainwindow", "Play Song", None, QtGui.QApplication.UnicodeUTF8))
        self.previousAction.setText(QtGui.QApplication.translate("mainwindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.nextAction.setText(QtGui.QApplication.translate("mainwindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setText(QtGui.QApplication.translate("mainwindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.importDirectoryAction.setText(QtGui.QApplication.translate("mainwindow", "Import Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.newPlaylistAction.setText(QtGui.QApplication.translate("mainwindow", "New Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.newRepositoryAction.setText(QtGui.QApplication.translate("mainwindow", "New Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCollectionAction.setText(QtGui.QApplication.translate("mainwindow", "Delete Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.modifyCollectionAction.setText(QtGui.QApplication.translate("mainwindow", "Modify Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.enqueueSongsAction.setText(QtGui.QApplication.translate("mainwindow", "Enqueue Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.clearSongQueueAction.setText(QtGui.QApplication.translate("mainwindow", "Clear Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteTagsAction.setText(QtGui.QApplication.translate("mainwindow", "Delete Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.renameTagsAction.setText(QtGui.QApplication.translate("mainwindow", "Rename Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.renameTagsAction.setToolTip(QtGui.QApplication.translate("mainwindow", "Rename one or more tags", None, QtGui.QApplication.UnicodeUTF8))

